Improved helper scripts and builder

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -5,17 +5,19 @@ BRANCH=$(git rev-parse --abbrev-ref HEAD)
 STAGING_IP=128.199.33.144
 PRODUCTION_IP=167.99.18.108
 
-if [[ $1 == "production" && $BRANCH != "main" ]]
+IP=$PRODUCTION_IP
+
+if [[ $BRANCH != "main" ]]
 then
   echo Wont deploy anything but main to production
   exit 1
 fi
 
-#if [[ -n $(git status --porcelain) ]]
-#then
-#  echo "Can't deploy while you have uncommited files"
-#  exit 1
-#fi
+if [[ -n $(git status --porcelain) ]]
+then
+  echo "Can't deploy while you have uncommited files"
+  exit 1
+fi
 
 if ! git pull origin $BRANCH
 then
@@ -29,12 +31,6 @@ fi
 #  exit 1
 #fi
 
-if [[ $1 == "production" ]]
-then
-  IP=$PRODUCTION_IP
-else
-  IP=$STAGING_IP
-fi
 
 until [[ -n $password ]]
 do
