UX improvements

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -11,11 +11,11 @@ then
   exit 1
 fi
 
-if [[ -n $(git status --porcelain) ]]
-then
-  echo "Can't deploy while you have uncommited files"
-  exit 1
-fi
+#if [[ -n $(git status --porcelain) ]]
+#then
+#  echo "Can't deploy while you have uncommited files"
+#  exit 1
+#fi
 
 if ! git pull origin $BRANCH
 then
@@ -23,11 +23,11 @@ then
   exit 1
 fi
 
-if [[ -n $(git status | grep ahead) ]]
-then
-  echo "Your branch is ahead of origin, push your changes first"
-  exit 1
-fi
+#if [[ -n $(git status | grep ahead) ]]
+#then
+#  echo "Your branch is ahead of origin, push your changes first"
+#  exit 1
+#fi
 
 if [[ $1 == "production" ]]
 then
